POST http://localhost:3001/api/products
content-type: application/json
{
    "name": "SEAT LEON CUPRA",
    "price": 45255,
    "manufacter": "B60258512",
}

### 
POST http://localhost:3001/api/products
content-type: application/json

{

}
